apiVersion: v2
name: ladedaten
description: Verwaltung eigener Wiederlade-Daten (Laborierungen, Testserien, Lose, Etiketten)
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords: [reloading, flask, mariadb]
