apiVersion: v2
name: ladedaten
description: Verwaltung eigener Wiederlade-Daten (Laborierungen, Testserien, Lose, Etiketten)
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords: [reloading, flask, mariadb]
