{{- if not .Values.auth.existingSecret }}
{{- $name := include "ladedaten.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "ladedaten.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ include "ladedaten.persistentSecret" (dict "ctx" . "secret" $name "key" "secret-key" "value" .Values.auth.secretKey) | b64enc | quote }}
  admin-username: {{ .Values.auth.adminUsername | b64enc | quote }}
  admin-password-hash: {{ .Values.auth.adminPasswordHash | b64enc | quote }}
{{- end }}
